name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: home

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t mightywomble/dockerforgebase_ubuntu:latest .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push mightywomble/dockerforgebase_ubuntu:lates

